### ISSUE TITLE
Error with logo displaying on the apps

### ISSUE THREAD

**Issue by ptxd** [swiperewards/Native---iOS#13]
There seems to be an issue with the app, where after several uses, typically two of the deals logo will not show up on the app until I make changes to the backend to reupdated the link.

Could be potentially a more serious issue here.

**Comment by ptxd** [comment]
![image](https://user-images.githubusercontent.com/27824585/46846640-53875780-cd95-11e8-8036-db58dc7db265.png)
image uploaded

**Comment by bharathwinjit** [comment]
There is no deal logo url from DealAPI. 
So If there is no deal logo , then we are showing Nouvo logo from app side manually.

**Comment by ptxd** [comment]
Issue seems to be solved at this stage
