### ISSUE TITLE
Redeem Mode Requirements

### ISSUE THREAD

**Issue by ptxd** [swiperewards/Native---iOS#9]
### **Bank Account**
Requires:

Name of bank
Account Number
Routing Number
Amount ( Allow 2 decimal points + validation checks)

### **Cryptocurrencies**
Requires:

List:
Bitcoin
BitcoinCash
Ethereum
Stellar
EOS

Wallet Address

Amount ( Allow 2 decimal points + validation checks)

### **Cheque**
Requires

Name
Address
Amount ( Allow 2 decimal points + validation checks)

_Remove Post -- Bug_

**Comment by ptxd** [comment]
Unable to use decimal points in withdrawal

**Comment by ptxd** [comment]
For Cheque change 'name as in bank' to "name"

**Comment by bharathwinjit** [comment]
To be tested in 1.0.4 [Completed]

**Comment by bharathwinjit** [comment]
> For Cheque change 'name as in bank' to "name"

To be tested in 1.0.4 [Completed]

**Comment by bharathwinjit** [comment]
> Unable to use decimal points in withdrawal

To be tested in 1.0.4 [Completed]

**Comment by ptxd** [comment]
Issues solved and closed
